# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('novices', models.TextField()),
                ('advanced_beginners', models.TextField()),
                ('competent', models.TextField()),
                ('proficient', models.TextField()),
                ('expert', models.TextField()),
                ('l1_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factor.L1Factor')),
            ],
        ),
    ]
